name: wechat_camera_picker_demo
description: A new Flutter project.
version: 4.2.0+31
publish_to: none

environment:
  sdk: ^3.2.0
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: '>=0.17.0 <1.0.0'

  wechat_camera_picker:
    path: ../

  package_info_plus: ^4.0.0
  video_player: ^2.7.0

dev_dependencies:
  flutter_lints: any

flutter:
  uses-material-design: true
  assets:
    - assets/
