name: wechat_camera_picker
version: 4.2.0-dev.4
description: |
  A camera picker for Flutter projects based on WeChat's UI,
  which is also a separate runnable extension to the
  wechat_assets_picker.
topics:
  - picker
  - camera
  - image
  - video
  - wechat

repository: https://github.com/fluttercandies/flutter_wechat_camera_picker
issue_tracker: https://github.com/fluttercandies/flutter_wechat_camera_picker/issues

environment:
  sdk: ^3.2.0
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter

  wechat_picker_library: ^1.0.0-0

  camera: ^0.10.0
  camera_platform_interface: ^2.1.5
  path: ^1.8.0
  photo_manager: ^3.0.0-dev.1
  photo_manager_image_provider: ^2.0.0
  sensors_plus: ^4.0.1
  video_player: ^2.7.0

dev_dependencies:
  flutter_lints: any

screenshots:
  - description: 'Screenshot 1'
    path: screenshots/README_1.jpg
  - description: 'Screenshot 2'
    path: screenshots/README_2.jpg
  - description: 'Screenshot 3'
    path: screenshots/README_3.jpg
  - description: 'Screenshot 4'
    path: screenshots/README_4.jpg
  - description: 'Screenshot 5'
    path: screenshots/README_5.jpg
