name: wechat_camera_picker
description: A camera picker which is an extension to wechat_assets_picker, but can be run separately.
version: 2.0.0-dev.3
homepage: https://github.com/fluttercandies/flutter_wechat_camera_picker

environment:
  sdk: ">=2.8.1 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.7.0
  device_info: ^1.0.0
  path_provider: ^1.6.27
  photo_manager: ^0.6.0
  video_player: ^1.0.1
