name: wechat_camera_picker
description: A camera picker which is an extension to wechat_assets_picker, but can be run separately.
version: 3.2.0-dev.1
homepage: https://github.com/fluttercandies/flutter_wechat_camera_picker

environment:
  sdk: '>=2.17.0-0 <3.0.0'
  flutter: '>=2.13.0-0'

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.9.4+21
  path: ^1.8.0
  path_provider: ^2.0.8
  photo_manager: ^2.0.8
  video_player: ^2.4.0
