name: wechat_camera_picker
description: A camera picker which is an extension to wechat_assets_picker, but can be run separately.
version: 3.4.0
homepage: https://github.com/fluttercandies/flutter_wechat_camera_picker

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  bindings_compatible: ^1.0.1
  camera: ^0.9.6
  camera_platform_interface: ^2.1.5
  path: ^1.8.0
  photo_manager: ^2.1.0+2
  video_player: ^2.3.2
