name: wechat_camera_picker
description: A camera picker based on WeChat's UI which is a separate runnable extension to wechat_assets_picker.
repository: https://github.com/fluttercandies/flutter_wechat_camera_picker
version: 3.7.0

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.10.0
  camera_platform_interface: ^2.1.5
  path: ^1.8.0
  photo_manager: ^2.4.0
  video_player: ^2.3.2
