name: wechat_camera_picker
description: A camera picker which is an extension to wechat_assets_picker, but can be run separately.
version: 2.6.2
homepage: https://github.com/fluttercandies/flutter_wechat_camera_picker

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.9.2+2
  path: ^1.8.0
  path_provider: ^2.0.2
  photo_manager: ^1.3.1
  video_player: ^2.1.14
